name: freelancer_invoice_app
description: "A Flutter application for freelancer invoicing"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_auth_web: ^5.8.1
  firebase_storage: ^11.5.6
  image_picker: ^1.0.7
  js: ^0.6.7
  file_picker: ^6.1.1
  path: ^1.8.3
  path_provider: ^2.1.2
  pdf: ^3.10.7
  printing: ^5.11.1
  intl: ^0.19.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14
  flutter_html: ^3.0.0-beta.2
  universal_html: ^2.2.4
  google_fonts: ^6.1.0
  web: ^0.1.4-beta
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - website/
    - website/index.html
    - website/css/
    - website/css/styles.css
    - website/css/placeholders.css
    - website/js/
    - website/js/main.js
    - website/images/ 